---
- name: Attempting to overlay resilio-sync yum repository
  tags: rslsync
  become: true
  yum_repository:
    baseurl: 'http://linux-packages.resilio.com/resilio-sync/rpm/$basearch'
    description: 'Resilio Sync $basearch'
    enabled: yes
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync'
    gpgcheck: yes
    name: resilio-sync
    state: present
  register: rslsync_yum_repository

- name: Downloading the resilio-sync gpg key to store locally
  tags: rslsync
  become: true
  get_url:
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync
    owner: root
    group: root
    mode: 0644
    url: 'https://linux-packages.resilio.com/resilio-sync/key.asc'
  register: rslsync_get_url

- name: Ensure that the resilio-sync gpg key is installed
  tags: rslsync
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync
    state: present
  register: rslsync_rpm_key
  when: rslsync_get_url is success

- name: Ensure that the resilio-sync package is installed
  tags: rslsync
  become: true
  yum:
   enablerepo: resilio-sync
   name: resilio-sync
   state: present
  register: rslsync_yum
  when:
    - rslsync_get_url is success
    - rslsync_rpm_key is success
    - rslsync_yum_repository is success

- name: Attempting to import resilio-sync tasks
  tags: rslsync
  become: true
  block:
    - import_tasks: rslsync_groupmod.yml
    - import_tasks: rslsync_directories.yml
    - import_tasks: rslsync_configuration.yml
    - import_tasks: rslsync_service.yml
  when: rslsync_yum is success
...
